services:
  drink-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/drink_tracker.db
      - PORT=8080
    env_file:
      - .env
    volumes:
      - sqlite_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data: