name: Deploy to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
        
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Set secrets
        run: |
          echo "${{ secrets.SLACK_BOT_TOKEN }}" | flyctl secrets set SLACK_BOT_TOKEN=-
          echo "${{ secrets.SLACK_SIGNING_SECRET }}" | flyctl secrets set SLACK_SIGNING_SECRET=-
          flyctl secrets set DATABASE_PATH=/data/drink_tracker.db
          flyctl secrets set AUTO_MIGRATE=true
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}