// Code generated by BobGen sqlite v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_test

import (
	models "github.com/aberyotaro/drink-tracker/models"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type DrinkRecord runs hooks after queries
var _ bob.HookableType = &models.DrinkRecord{}

// Make sure the type DrinkType runs hooks after queries
var _ bob.HookableType = &models.DrinkType{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}
